gabrieliaus_servisas/autoservisas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("carmodels/", views.carmodels, name="carmodels"),
    path("partservices/", views.partservices, name="partservices"),
    path("orderlines", views.orderlines, name="orderlines"),
    path('cardetail/<int:pk>/', views.car_detail, name='car_detail'),
    path('partservice/<int:pk>/', views.PartServiceDetailView.as_view(), name="partservice_detail"),
    path("masinos/mano/", views.CarUserListView.as_view(), name="cars_user"),
    path('cars/add/', views.CarCreateView.as_view(), name='car_add'),
    path('cars/<int:pk>/edit/', views.CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete/', views.CarDeleteView.as_view(), name='car_delete'),
    path('create_partservice/<int:car_id>/', views.create_partservice_for_car, name='create_partservice'),
    path('user_part_service_detail/<int:car_id>/', views.user_part_service_detail, name='user_part_service_detail'),
    path('user_part_service_detail/<int:pk>/update/', views.CarPartServiceUpdateView.as_view(), name='carpartservice_update'),
    path('user_part_service_detail/<int:pk>/delete/', views.CarPartServiceDeleteView.as_view(), name='carpartservice_delete'),
]

gabrieliaus_servisas/gabrieliaus_servisas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autoservisas.urls')),
    path('user/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/translations/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
] + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

gabrieliaus_servisas/autoservisas/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

User = get_user_model()


class CarModel(models.Model):
    brand = models.CharField(_("brand"), max_length=50, db_index=True)
    model = models.CharField(_("model"), max_length=50, db_index=True)
    year = models.IntegerField(_("year"), db_index=True)
    cover = models.ImageField(_("cover"), upload_to='carmodel_covers', null=True, blank=True)

    class Meta:
        verbose_name = _("carmodel")
        verbose_name_plural = _("carmodels")
        ordering = ["brand", "model", "year"]

    def __str__(self):
        return f"{self.brand} {self.model} {self.year}"

    def get_absolute_url(self):
        return reverse("carmodel_detail", kwargs={"pk": self.pk})
    

class Car(models.Model):
    customer = models.CharField(_("customer"), max_length=50, db_index=True)
    car_model = models.ForeignKey(
        CarModel,
        verbose_name=_("carmodel"),
        on_delete=models.CASCADE,
        related_name="cars",
        )
    plate = models.CharField(_("plate"), max_length=10)
    vin = models.CharField(_("vin"), max_length=17)
    color = models.CharField(_("color"), max_length=20)
    owner = models.ForeignKey(User, verbose_name=_("owner"), on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = _("car")
        verbose_name_plural = _("cars")
        ordering = ["customer"]

    def __str__(self):
        return f"{self.customer} {self.plate} {self.vin}"

    def get_absolute_url(self):
        return reverse("car_detail", kwargs={"pk": self.pk})


SERVICEORDER_STATUS = (
    (0, _("pending")),
    (1, _("in progress")),
    (2, _("completed")),
    (3, _("cancelled")),
)


class ServiceOrder(models.Model):
    car = models.ForeignKey(
        Car,
        verbose_name=_("car"),
        on_delete=models.CASCADE,
        related_name="orders",
        db_index=True,
    )
    date = models.DateField(_("date"), auto_now=False, auto_now_add=True)
    status = models.PositiveSmallIntegerField(
        _("status"),
        choices=SERVICEORDER_STATUS, 
        default=0
    )

    class Meta:
        verbose_name = _("serviceorder")
        verbose_name_plural = _("serviceorders")
        ordering = ["car"]

    def __str__(self):
        return f"{self.id} {self.date} {self.get_status_display()}"

    def get_absolute_url(self):
        return reverse("serviceorder_detail", kwargs={"pk": self.pk})


class PartService(models.Model):
    name = models.CharField(_("name"), max_length=50, db_index=True)
    price = models.DecimalField(_("price"), max_digits=18, decimal_places=2)
    about = HTMLField(_("about"), max_length=10000, default='', blank=True)

    class Meta:
        verbose_name = _("partservice")
        verbose_name_plural = _("partservices")
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} Kaina {self.price}"

    def get_absolute_url(self):
        return reverse("partservice_detail", kwargs={"pk": self.pk}) 

class PartServiceReview(models.Model):
    partservice = models.ForeignKey(
        PartService, 
        verbose_name=_("partservice"),
        on_delete=models.CASCADE,
        related_name='reviews',
    )
    reviewer = models.ForeignKey(
        User, 
        verbose_name=_("reviewer"), 
        on_delete=models.CASCADE,
        related_name='partservice_reviews',
    )
    content = models.TextField(_("Content"), max_length=4000)
    created_at = models.DateTimeField(
        _("created at"), 
        auto_now_add=True, 
        db_index=True
    )
    class Meta:
        verbose_name = _("partservice review")
        verbose_name_plural = _("partservice reviews")
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.partservice} review by {self.reviewer}"

    def get_absolute_url(self):
        return reverse("partservicereview_detail", kwargs={"pk": self.pk})


class OrderLine(models.Model):
    order = models.ForeignKey(
        ServiceOrder,
        verbose_name=_("order"),
        on_delete=models.CASCADE,
        related_name="lines",
        db_index=True,
        )
    part_service = models.ForeignKey(
        PartService,
        verbose_name=_("part service id"),
        on_delete=models.CASCADE,
        related_name="lines",
        )
    quantity = models.IntegerField(_("quantity"), default=1)
    price = models.DecimalField(_("price"), max_digits=18, decimal_places=2)
    
    class Meta:
        verbose_name = _("orderline")
        verbose_name_plural = _("orderlines")
        ordering = ["order"]

    def __str__(self):
        return f"{self.order} {self.part_service} Kiekis {self.quantity} Papildomos išlaidos {self.price}"

    def get_absolute_url(self):
        return reverse("orderline_detail", kwargs={"pk": self.pk})
    
    @property
    def calculate_total(self):
        total = self.quantity * self.price + self.part_service.price
        return total
    
class CarPartService(models.Model):
    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        related_name='car_part_services',
    )
    part_service = models.ForeignKey(
        PartService,
        on_delete=models.CASCADE,
        related_name='car_part_services',
    )
    problem = HTMLField(_("problem"), max_length=10000, default='', blank=True)
    def __str__(self):
        return f"{self.car} - {self.part_service} - {self.problem}"

gabrieliaus_servisas/autoservisas/forms.py
from django import forms
from . import models


class PartServiceReviewForm(forms.ModelForm):
    class Meta:
        model = models.PartServiceReview
        fields = ('content', 'partservice', 'reviewer')
        widgets = {
            'partservice': forms.HiddenInput(),
            'reviewer': forms.HiddenInput(),
        }
        labels = {
            'content': '',
        }

class CarForm(forms.ModelForm):
    class Meta:
        model = models.Car
        fields = ['car_model', 'plate', 'vin', 'color']
        labels = {
            'car_model': 'Mašinos modelis',
            'plate': 'Numeris',
            'vin': 'VIN',
            'color': 'Spalva',
        }

class PartServiceForm(forms.ModelForm):
    part_service = forms.ModelChoiceField(
        queryset=models.PartService.objects.all(),
        label='Pasirinkite paslaugą',
    )

    class Meta:
        model = models.CarPartService
        fields = ['part_service', 'problem'] 
        labels = {
            'problem': 'Aprašykite problemą',
        }

gabrieliaus_servisas/autoservisas/views.py
from typing import Any
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models.query import QuerySet, Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . import models, forms
from django.utils.translation import gettext_lazy as _

class CarUserListView(LoginRequiredMixin, generic.ListView):
    model = models.Car
    template_name = "autoservisas/car_user_list.html"
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset

def index(request):
    context = {
        "num_carmodels": models.CarModel.objects.count(),
        "num_cars": models.Car.objects.count(),
        "num_service_orders": models.ServiceOrder.objects.count(),
        "num_partservice": models.PartService.objects.count(),
        "num_orderlines": models.OrderLine.objects.count(),
        "car_model_brands": models.CarModel.objects.values_list("brand", flat=True).distinct(),
        "partandservice": models.PartService.objects.values_list("name", "price").distinct()
    }
    return render(request, "autoservisas/index.html", context)

def carmodels(request):
    query = request.GET.get('query', '')
    carmodels_query = models.CarModel.objects.all()
    if query:
        carmodels_query = carmodels_query.filter(
            Q(brand__icontains=query) | Q(model__icontains=query)
        )
    carmodels_pages = Paginator(carmodels_query, 3)
    current_page = request.GET.get('page') or 1
    current_page_obj = carmodels_pages.get_page(current_page)
    context = {
        "carmodels": current_page_obj,
    }
    return render(request, "autoservisas/carmodels.html", context)

def partservices(request):
    return render(
        request,
        "autoservisas/partservices.html",
        {"partservices": models.PartService.objects.all()}
    )

def orderlines(request):
    orderlines = models.OrderLine.objects.all().order_by('order__date')
    return render(
        request,
        "autoservisas/orderlines.html",
        {"orderlines": orderlines}
    )

def car_detail(request, pk):
    return render(
        request,
        "autoservisas/car_detail.html",
        {"car_detail": get_object_or_404(models.Car, pk=pk)}
    )

def orderlines(request):
    query = request.GET.get('uzsakymai', '')
    orderlines_query = models.OrderLine.objects.all()
    if query:
        orderlines = orderlines_query.filter(
            Q(order__car__customer__icontains=query) |
            Q(part_service__name__icontains=query) |
            Q(order__status__icontains=query) 
        ).order_by('order__date')
    else:
        orderlines = orderlines_query.order_by('order__date')
    orderlines_pages = Paginator(orderlines, 2)
    current_page = request.GET.get('page') or 1
    current_page_obj = orderlines_pages.get_page(current_page)
    context = {
        "orderlines": current_page_obj,
        "all_orderlines": orderlines, 
    }
    return render(request, "autoservisas/orderlines.html", context)


class PartServiceDetailView(generic.edit.FormMixin, generic.DetailView):
    model = models.PartService
    template_name = 'autoservisas/partservice_detail.html'
    form_class = forms.PartServiceReviewForm

    def get_initial(self) -> dict[str, Any]:
        initial = super().get_initial()
        initial['partservice'] = self.get_object()
        initial['reviewer'] = self.request.user
        return initial

    def post(self, *args, **kwargs) -> HttpResponse:
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form) -> HttpResponse:
        form.instance.partservice = self.object
        form.instance.reviewer = self.request.user
        form.save()
        messages.success(self.request, _('Atsiliepimas pridėtas sėkmingai.'))
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse('partservice_detail', kwargs={'pk': self.object.pk})
    
class CarCreateView(LoginRequiredMixin, CreateView):
    model = models.Car
    form_class = forms.CarForm
    template_name = 'autoservisas/car_form.html'
    success_url = reverse_lazy('cars_user')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, 'Mašina pridėta sėkmingai.')
        return super().form_valid(form)

class CarUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Car
    form_class = forms.CarForm
    template_name = 'autoservisas/car_form.html'
    success_url = reverse_lazy('cars_user')

    def form_valid(self, form):
        messages.success(self.request, 'Mašina pakeista sėkmingai.')
        return super().form_valid(form)

class CarDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Car
    template_name = 'autoservisas/car_confirm_delete.html'
    success_url = reverse_lazy('cars_user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = self.get_object()
        context['car'] = car
        return context

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
    def get_success_url(self):
        messages.success(self.request, 'Mašina ištrinta sėkmingai.')
        return reverse('cars_user')

def create_partservice_for_car(request, car_id):
    car = get_object_or_404(models.Car, pk=car_id, owner=request.user)
    if request.method == 'POST':
        form = forms.PartServiceForm(request.POST)
        if form.is_valid():
            part_service = form.cleaned_data['existing_part_service']
            problem = form.cleaned_data['problem']
            car_part_service = models.CarPartService(
                car=car,
                part_service=part_service,
                problem=problem
            )
            car_part_service.save()
            
            return redirect('cars_user')
    else:
        form = forms.PartServiceForm()
    
    existing_partservices = models.PartService.objects.all()

    context = {
        'car': car,
        'form': form,
        'existing_partservices': existing_partservices,
    }
    return render(request, 'autoservisas/create_partservice.html', context)


def user_part_service_detail(request, car_id):
    car = get_object_or_404(models.Car, pk=car_id, owner=request.user)
    partservices = models.CarPartService.objects.filter(car=car).select_related('part_service')
    
    context = {
        'car': car,
        'partservices': partservices,
    }
    return render(request, 'autoservisas/user_part_service_detail.html', context)


class CarPartServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = models.CarPartService
    form_class = forms.PartServiceForm
    template_name = 'autoservisas/create_partservice.html'

    def get_success_url(self):
        return reverse('user_part_service_detail', kwargs={'car_id': self.object.car.id})

    def form_valid(self, form):
        messages.success(self.request, 'Paslauga atnaujinta sėkmingai.')
        return super().form_valid(form)

class CarPartServiceDeleteView(LoginRequiredMixin, DeleteView):
    model = models.CarPartService
    template_name = 'autoservisas/carpartservice_confirm_delete.html'
    success_url = reverse_lazy('user_part_service_detail')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        carpartservice = self.get_object()
        context['carpartservice'] = carpartservice
        return context

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, 'Paslauga ištrinta sėkmingai.')
        return reverse('user_part_service_detail', kwargs={'car_id': self.object.car.id})

gabrieliaus_servisas/autoservisas/templates/autoservisas/car_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}Patvirtinimas {{ block.super }}{% endblock title %}
{% block content %}
<h1>Patvirtinimas</h1>
<p>Ar tikrai norite ištrinti šią mašiną "<strong>{{ car.car_model.brand }} {{ car.car_model.model }} {{ car.car_model.year }} {{ car.plate }}</strong>"?</p>
<form method="post">
    {% csrf_token %}
    <p><button type="submit">Taip</button></p>
</form>
<p><a href="{% url 'cars_user' %}">Grįžti</a></p>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/car_detail.html
{% extends "base.html" %}
{% block title %}Mašina {{ block.super }}{% endblock title %}
{% block content %}
<h1>{{ car_detail.customer }} mašina</h1>
{% if car_detail %}
    <table class="car-center">
        <tr>
            <th>Ženklas</th>
            <th>Modelis</th>
            <th>Metai</th>
            <th>Numeris</th>
            <th>VIN</th>
            <th>Spalva</th>
        </tr>
        <tr class="data-row">
            <td>{{ car_detail.car_model.brand }}</td>
            <td>{{ car_detail.car_model.model }}</td>
            <td>{{ car_detail.car_model.year }}</td>
            <td>{{ car_detail.plate }}</td>
            <td>{{ car_detail.vin }}</td>
            <td>{{ car_detail.color }}</td>
        </tr>
    </table>
{% endif %}
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/car_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pridėjimas {{ block.super }}{% endblock title %}
{% block content %}
<h1>Pridėti mašiną</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Pridėti</button></p>
</form>
<p><a href="{% url 'cars_user' %}">Grįžti</a></p>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/car_user_list.html
{% extends "base.html" %}
{% block title %}Mašinos {{ block.super }}{% endblock title %}
{% block content %}
<h1>Mano mašinos<a class="float-right btn" href="{% url "car_add" %}">Pridėti mašiną</a></h1>
{% if car_list %}
    <table class="car-center">
        <tr>
            <th>Ženklas</th>
            <th>Modelis</th>
            <th>Metai</th>
            <th>Numeris</th>
            <th>VIN</th>
            <th>Spalva</th>
            <th>Veiksmai</th>
        </tr>
    {% for car in car_list %}
        <tr class="data-row">
            <td>{{ car.car_model.brand }}</td>
            <td>{{ car.car_model.model }}</td>
            <td>{{ car.car_model.year }}</td>
            <td>{{ car.plate }}</td>
            <td>{{ car.vin }}</td>
            <td>{{ car.color }}</td>
            <td>
                <a href="{% url 'car_edit' car.pk %}" class="btn btn-info">Pakeisti</a> |
                <a href="{% url 'car_delete' car.pk %}" class="btn btn-danger">Ištrinti</a> |
                <a href="{% url 'create_partservice' car.id %}" class="btn btn-primary">Pridėti paslaugą</a>
                <a href="{% url 'user_part_service_detail' car.id %}" class="btn btn-secondary">Paslaugos</a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>Mašinų nėra.</p>
{% endif %}
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/carmodels.html
{% extends "base.html" %}
{% load static %}
{% block title %}Mašinos {{ block.super }}{% endblock title %}
{% block content %}
<h1>Mašinos, kurias tvarkome</h1>
{% include "autoservisas/inc/pager_prev_next.html" %}
<div class="card-list">
    {% for carmodel in carmodels %}
    <div class="card">
        <a href="{% url 'partservices' %}">
        <div class="card-content">
            {% if carmodel.cover %}
                <img class="car-cover" src="{{ carmodel.cover.url }}" alt="{{ carmodel.brand }} {{ carmodel.model }}">
            {% else %}
                <img class="car-cover" src="{% static 'img/default_cover.png' %}" alt="Default Car Image">
            {% endif %}
                <h4>{{ carmodel.brand }}</h4>
                <h4>{{ carmodel.model }}</h4>
                <h4>{{ carmodel.year }}</h4>
        </div></a>
    </div>
    {% empty %}
    <p>Nerasta...</p>
    {% endfor %}
</div>
{% include "autoservisas/inc/pager_pages.html" %}
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/carpartservice_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}Ištrinti Paslaugą{{ block.super }}{% endblock title %}
{% block content %}
<div class="container">
  <h2>Ištrinti Paslaugą</h2>
  <p>Ar tikrai norite ištrinti šią paslaugą?</p>
  <form method="post">
    {% csrf_token %}
    <p>Paslaugos pavadinimas: {{ object.part_service.name }}</p>
    <p>Kaina: {{ object.part_service.price }}</p>
    <p>Problema: {{ object.problem }}</p>
    <button type="submit" class="btn btn-danger">Ištrinti</button>
  </form>
</div>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/create_partservice.html
{% extends "base.html" %}
{% block title %}Pridėjimas {{ block.super }}{% endblock title %}
{% block content %}
<h1>Pridėti paslaugą mašinai "{{ car.plate }}"</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit" class="btn btn-success">Pridėti paslaugą</button></p>
</form>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "namai"|title %} {{ block.super }}{% endblock title %}
{% block content %}
<h1>{% trans "sveiki atvykę į autoservisą"|capfirst %}!</h1>
<p>{% trans "dabar servise turime:"|capfirst %}</p>
<ul>
    <li>{% trans "mašinų modeliai" %}: <span class="num">{{ num_carmodels }}</span></li>
    <li>{% trans "remontuojamų mašinų kiekis" %}: <span class="num">{{ num_cars }}</span></li>
    <li>{% trans "atliekamų paslaugų kiekis" %}: <span class="num">{{ num_partservice }}</span></li>
    <li>{% trans "užsakymų kiekis" %}: <span class="num">{{ num_orderlines }}</span></li>
</ul>
<h2>{% trans "mašinų ženklai"|capfirst %}</h2>
<ul>
    {% for brand in car_model_brands %}
      <li>{{ brand }}</li>
    {% endfor %}
</ul>
<h2>{% trans "paslaugos"|title %}</h2>
<ul>
    {% for part in partandservice %}
      <li>{{ part.0 }} {{ part.1|floatformat:2 }}</li>
    {% endfor %}
</ul>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/orderlines.html
{% extends "base.html" %}
{% block title %}Užsakymai {{ block.super }}{% endblock title %}
{% block content %}
<h1>Užsakymai</h1>
{% include "autoservisas/inc/pager_uzsakymai.html" %}
{% if all_orderlines %}
    <table class="orderlines-center">
        <tr>
            <th>Užsakymas</th>
            <th>Statusas</th>
            <th>Klientas</th>
            <th>Paslauga</th>
            <th>Paslaugos kaina</th>
            <th>Kiekis</th>
            <th>Papildomos išlaidos</th>
            <th>Iš viso</th>
            <th>Data</th>
        </tr>
        {% for orderline in orderlines %}
            <tr class="data-row">
                <td>{{ orderline.order.id }}</td>
                <td class="{% if orderline.order.status == 0 %}
                status-pending
                {% elif orderline.order.status == 1 %}
                status-in-progress
                {% elif orderline.order.status == 2 %}
                status-completed
                {% elif orderline.order.status == 3 %}
                status-cancelled
                {% endif %}">
                {{ orderline.order.get_status_display }}</td>
                <td><a href="{% url 'car_detail' orderline.order.car.pk %}">{{ orderline.order.car.customer }}</a></td>
                <td>{{ orderline.part_service.name }}</td>
                <td>{{ orderline.part_service.price }}</td>
                <td>{{ orderline.quantity }}</td>
                <td>{{ orderline.price }}</td>
                <td>{{ orderline.calculate_total }}</td>
                <td>{{ orderline.order.date }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
<p>Nerasta...</p>
{% endif %}
{% include "autoservisas/inc/pager_pages_uzsakymai.html" %}
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/partservice_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Paslauga {{ block.super }}{% endblock title %}
{% block content %}
<h1>{{ partservice.name }}</h1>
    {{ partservice.about|safe }}
<h2>Atsiliepimai</h2>
{% if user.is_authenticated %}
<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Komentuoti</button></p>
</form>
{% endif %}
{% if partservice.reviews.all %}
<ul class="nice-list">
    {% for review in partservice.reviews.all %}
        <li>
            <h4>
                <span>{{ review.reviewer }}</span>
                <span class="float-right">{{ review.created_at}}</span>
            </h4>
            <em>{{ review.content }}</em>
        </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/partservices.html
{% extends "base.html" %}
{% block title %}Paslaugos {{ block.super }}{% endblock title %}
{% block content %}
<h1>Paslaugos, kurias atliekame</h1>
<div class="service-cards">
    {% for partservice in partservices.all %}
    <div class="service-card">
        <a href="{% url 'partservice_detail' partservice.pk %}">
        <h2>{{ partservice.name }}</h2>
        <p class="price">{{ partservice.price }}</p>
    </div></a>
    {% endfor %}
</div>
{% endblock content %}

gabrieliaus_servisas/autoservisas/templates/autoservisas/user_part_service_detail.html
{% extends "base.html" %}
{% block title %}Mašinos Paslaugos{{ block.super }}{% endblock title %}
{% block content %}
<h1>Paslaugos susijusios su {{ car.car_model.brand }} {{ car.car_model.model }}</h1>
{% if partservices %}
    <table class="car-center">
        <tr>
            <th>Paslaugos pavadinimas</th>
            <th>Kaina</th>
            <th>Problema</th>
            <th>Veiksmai</th>  <!-- Add a column for actions -->
        </tr>
    {% for partservice in partservices %}
        <tr class="data-row">
            <td>{{ partservice.part_service.name }}</td>
            <td>{{ partservice.part_service.price }}</td>
            <td>{{ partservice.problem }}</td>
            <td>
                <a href="{% url 'carpartservice_update' partservice.pk %}" class="btn btn-danger">Atnaujinti</a>
                <a href="{% url 'carpartservice_delete' partservice.pk %}" class="btn btn-danger">Ištrinti</a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>Šiai mašinai nėra susijusių paslaugų.</p>
{% endif %}
{% endblock content %}